import {requireSession,currentUser,select,patch,insert,signOut} from './api.js';
import {buildContentPack} from './content-factory.js';
let session=null, snapshot=null, pendingContent=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Date(d).toLocaleString():'—';
const countBy=(rows,key)=>rows.reduce((m,r)=>(m[r[key]||'unknown']=(m[r[key]||'unknown']||0)+1,m),{});
function breakdown(host,obj){host.innerHTML=Object.entries(obj).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="breakdown-row"><span>${esc(k)}</span><strong>${v}</strong></div>`).join('')||'<p class="empty">No data yet.</p>'}
async function assertAdmin(user,token){const rows=await select('dfqi_admin_users',`select=user_id,role,display_name&user_id=eq.${encodeURIComponent(user.id)}&active=eq.true`,token);if(!Array.isArray(rows)||rows.length===0)throw new Error('This account is not authorised for the DFQI admin workspace.');return rows[0]}
export async function tryRestoreAdmin(){session=await requireSession();if(!session)return false;try{const user=await currentUser(session.access_token);await assertAdmin(user,session.access_token);showAdmin(user);await loadDashboard();return true}catch{await signOut();session=null;return false}}
export async function enterAdmin(authData){session=authData;const user=authData.user||await currentUser(authData.access_token);try{await assertAdmin(user,authData.access_token)}catch(e){await signOut();session=null;throw e}showAdmin(user);await loadDashboard()}
function showAdmin(user){$('#admin-auth-card').hidden=true;$('#admin-app').hidden=false;$('#admin-user-label').textContent=user.email||'Signed in'}
export async function leaveAdmin(){await signOut();session=null;$('#admin-app').hidden=true;$('#admin-auth-card').hidden=false;$('#admin-login-form').reset()}
export function bindAdminUI(){
 $('#admin-signout').onclick=leaveAdmin;
 document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-admin-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-admin-panel]').forEach(p=>p.classList.toggle('active',p.dataset.adminPanel===b.dataset.adminTab))});
 $('#content-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);pendingContent={source_truth:f.get('source_truth'),audience:f.get('audience'),objective:f.get('objective')};pendingContent.output=buildContentPack(pendingContent.source_truth,pendingContent.audience,pendingContent.objective);$('#content-output').textContent=pendingContent.output;$('#save-content').disabled=false};
 $('#copy-content').onclick=()=>navigator.clipboard.writeText($('#content-output').textContent);
 $('#save-content').onclick=saveContent;
 $('#config-form').onsubmit=saveConfig;
 $('#export-contacts').onclick=exportContacts;
 $('#journey-close').onclick=()=>$('#journey-dialog').close();
}
async function loadDashboard(){const t=session.access_token;const [contacts,assessments,intents,orgs,events,contents,config,masterclasses,tasks]=await Promise.all([
 select('dfqi_contacts','select=*&order=created_at.desc&limit=500',t),select('dfqi_readiness_assessments','select=*&order=created_at.desc&limit=500',t),select('dfqi_enrolment_intents','select=*&order=created_at.desc&limit=500',t),select('dfqi_organisation_leads','select=*&order=created_at.desc&limit=500',t),select('dfqi_events','select=*&order=occurred_at.desc&limit=1000',t),select('dfqi_content_assets','select=*&order=created_at.desc&limit=200',t),select('dfqi_program_config','select=*&order=key',t),select('dfqi_masterclass_registrations','select=*&order=created_at.desc&limit=500',t),select('dfqi_followup_tasks','select=*&order=created_at.desc&limit=500',t)]);snapshot={contacts,assessments,intents,orgs,events,contents,config,masterclasses,tasks};renderAll()}
function renderAll(){const s=snapshot;const openTasks=s.tasks.filter(x=>['open','in_progress'].includes(x.status)).length;const metrics=[['Contacts',s.contacts.length],['Diagnostics',s.assessments.length],['Programme intents',s.intents.length],['Organisation leads',s.orgs.length],['Open follow-ups',openTasks]];$('#admin-kpis').innerHTML=metrics.map(([l,v])=>`<div class="kpi"><span>${l}</span><strong>${v}</strong></div>`).join('');breakdown($('#source-breakdown'),countBy(s.events,'source'));breakdown($('#route-breakdown'),countBy(s.assessments,'recommended_route'));$('#events-table').innerHTML=s.events.slice(0,60).map(r=>`<tr><td>${fmt(r.occurred_at)}</td><td>${esc(r.event_name)}</td><td>${esc(r.route||'—')}</td><td>${esc(r.source||'—')}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No events yet.</td></tr>';renderPeople();renderTasks();renderMasterclasses();renderOrgs();renderContent();renderConfig()}
function latestFor(rows,id,key='contact_id'){return rows.filter(x=>x[key]===id).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]}
function renderPeople(){const s=snapshot;$('#people-table').innerHTML=s.contacts.map(c=>{const a=latestFor(s.assessments,c.id),i=latestFor(s.intents,c.id);return`<tr><td><strong>${esc(c.full_name)}</strong><br><small>${esc(c.email)}</small></td><td>${esc(c.part1_status)}</td><td>${esc(a?.recommended_route||'—')}</td><td>${esc(i?.requested_program||'—')}</td><td>${i?statusSelect('intent-status',i.id,i.status,['new','contacted','eligibility_review','confirmed','waitlisted','declined','withdrawn']):'—'}</td><td>${i?statusSelect('handoff-status',i.id,i.registration_handoff_status,['not_started','sent','completed','not_required']):'—'}</td><td><button class="btn quiet journey-btn" data-id="${c.id}">View</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No contacts yet.</td></tr>';document.querySelectorAll('.intent-status').forEach(x=>x.onchange=()=>updateIntent(x.dataset.id,{status:x.value}));document.querySelectorAll('.handoff-status').forEach(x=>x.onchange=()=>updateIntent(x.dataset.id,{registration_handoff_status:x.value}));document.querySelectorAll('.journey-btn').forEach(x=>x.onclick=()=>showJourney(x.dataset.id))}
function statusSelect(cls,id,value,options){return`<select class="status-select ${cls}" data-id="${id}">${options.map(o=>`<option ${o===value?'selected':''} value="${o}">${o}</option>`).join('')}</select>`}
async function updateIntent(id,row){await patch('dfqi_enrolment_intents',`id=eq.${id}`,row,session.access_token);await loadDashboard()}
function showJourney(contactId){const c=snapshot.contacts.find(x=>x.id===contactId);if(!c)return;const assessments=snapshot.assessments.filter(x=>x.contact_id===contactId).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const intents=snapshot.intents.filter(x=>x.contact_id===contactId).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const masterclasses=snapshot.masterclasses.filter(x=>x.contact_id===contactId).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));const events=snapshot.events.filter(x=>x.contact_id===contactId).sort((a,b)=>new Date(a.occurred_at)-new Date(b.occurred_at));$('#journey-title').textContent=c.full_name;const blocks=[];blocks.push(`<div class="journey-summary"><div><span>First source</span><strong>${esc(c.first_source||'direct')}</strong></div><div><span>Part 1 status</span><strong>${esc(c.part1_status)}</strong></div><div><span>Current intent</span><strong>${esc(intents.at(-1)?.requested_program||'—')}</strong></div></div>`);if(assessments.length)blocks.push(`<h3>Readiness assessments</h3>${assessments.map(a=>`<div class="journey-row"><span>${fmt(a.created_at)}</span><strong>${a.score}% · ${esc(a.recommended_route)}</strong></div>`).join('')}`);if(masterclasses.length)blocks.push(`<h3>Mini-Masterclasses</h3>${masterclasses.map(m=>`<div class="journey-row"><span>${fmt(m.created_at)}</span><strong>${esc(m.session_slug)} · ${esc(m.status)}</strong></div>`).join('')}`);if(intents.length)blocks.push(`<h3>Programme intents</h3>${intents.map(i=>`<div class="journey-row"><span>${fmt(i.created_at)}</span><strong>${esc(i.requested_program)} · ${esc(i.pathway)} · ${esc(i.status)}</strong></div>`).join('')}`);if(events.length)blocks.push(`<h3>Attributed activity</h3>${events.slice(-20).map(e=>`<div class="journey-row"><span>${fmt(e.occurred_at)}</span><strong>${esc(e.event_name)}${e.route?' · '+esc(e.route):''}</strong></div>`).join('')}`);$('#journey-body').innerHTML=blocks.join('')||'<p class="empty">No journey history yet.</p>';$('#journey-dialog').showModal()}

function renderOrgs(){const opts=['new','contacted','qualified','proposal','confirmed','closed','not_a_fit'];$('#org-table').innerHTML=snapshot.orgs.map(o=>`<tr><td><strong>${esc(o.organization_name)}</strong></td><td>${esc(o.contact_name)}<br><small>${esc(o.email)}</small></td><td>${esc(o.team_size||'—')}</td><td>${esc(o.primary_need||'—')}</td><td>${statusSelect('org-status',o.id,o.status,opts)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No organisation leads yet.</td></tr>';document.querySelectorAll('.org-status').forEach(x=>x.onchange=async()=>{await patch('dfqi_organisation_leads',`id=eq.${x.dataset.id}`,{status:x.value},session.access_token);await loadDashboard()})}
function contactName(id){const c=snapshot.contacts.find(x=>x.id===id);return c?`${c.full_name} (${c.email})`:id||'—'}
function organisationName(id){const o=snapshot.orgs.find(x=>x.id===id);return o?o.organization_name:id||'—'}
function renderTasks(){const opts=['open','in_progress','done','cancelled'];$('#tasks-table').innerHTML=snapshot.tasks.map(t=>`<tr><td>${fmt(t.created_at)}</td><td><strong>${esc(t.title)}</strong><br><small>${esc(t.task_type)}</small></td><td>${esc(t.contact_id?contactName(t.contact_id):organisationName(t.organisation_lead_id))}</td><td>${statusSelect('task-status',t.id,t.status,opts)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No follow-up tasks yet.</td></tr>';document.querySelectorAll('.task-status').forEach(x=>x.onchange=async()=>{await patch('dfqi_followup_tasks',`id=eq.${x.dataset.id}`,{status:x.value,updated_at:new Date().toISOString()},session.access_token);await loadDashboard()})}
function renderMasterclasses(){const opts=['registered','attended','proof_submitted','completed','no_show'];$('#masterclass-table').innerHTML=snapshot.masterclasses.map(m=>`<tr><td>${esc(contactName(m.contact_id))}</td><td>${esc(m.session_slug)}</td><td>${statusSelect('masterclass-status',m.id,m.status,opts)}</td><td><input class="proof-input" data-id="${m.id}" value="${esc(m.proof_summary||'')}" placeholder="Optional proof summary"></td></tr>`).join('')||'<tr><td colspan="4" class="empty">No Mini-Masterclass registrations yet.</td></tr>';document.querySelectorAll('.masterclass-status').forEach(x=>x.onchange=async()=>{await patch('dfqi_masterclass_registrations',`id=eq.${x.dataset.id}`,{status:x.value,updated_at:new Date().toISOString()},session.access_token);await loadDashboard()});document.querySelectorAll('.proof-input').forEach(x=>x.onchange=async()=>{await patch('dfqi_masterclass_registrations',`id=eq.${x.dataset.id}`,{proof_summary:x.value||null,updated_at:new Date().toISOString()},session.access_token)})}
function renderContent(){const status=['draft','review','approved','published','archived'],fact=['pending','passed','changes_needed'],clinical=['pending','passed','not_required','changes_needed'];$('#content-table').innerHTML=snapshot.contents.map(c=>`<tr><td>${fmt(c.created_at)}</td><td>${esc(c.audience)}</td><td>${esc(c.objective)}</td><td>${statusSelect('content-status',c.id,c.status,status)}</td><td>Fact: ${statusSelect('content-fact',c.id,c.factual_review_status,fact)}<br>Clinical: ${statusSelect('content-clinical',c.id,c.clinical_review_status,clinical)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No content assets yet.</td></tr>';document.querySelectorAll('.content-status').forEach(x=>x.onchange=()=>updateContent(x.dataset.id,{status:x.value}));document.querySelectorAll('.content-fact').forEach(x=>x.onchange=()=>updateContent(x.dataset.id,{factual_review_status:x.value}));document.querySelectorAll('.content-clinical').forEach(x=>x.onchange=()=>updateContent(x.dataset.id,{clinical_review_status:x.value}))}
async function updateContent(id,row){await patch('dfqi_content_assets',`id=eq.${id}`,{...row,updated_at:new Date().toISOString()},session.access_token);await loadDashboard()}
async function saveContent(){if(!pendingContent)return;await insert('dfqi_content_assets',{created_by:session.user?.id||null,source_truth:pendingContent.source_truth,audience:pendingContent.audience,objective:pendingContent.objective,outputs:{pack:pendingContent.output}},session.access_token);pendingContent=null;$('#save-content').disabled=true;$('#content-form').reset();await loadDashboard()}
function renderConfig(){const form=$('#config-form');const map=Object.fromEntries(snapshot.config.map(x=>[x.key,x.value]));form.part2_dates.value=map.part2_dates??'';form.part2_fee.value=map.part2_fee??'';form.delivery_mode.value=map.delivery_mode??'Live online + coaching';form.prerequisite_policy.value=map.prerequisite_policy??'equivalency'}
async function saveConfig(e){e.preventDefault();const f=new FormData(e.currentTarget);for(const key of ['part2_dates','part2_fee','delivery_mode','prerequisite_policy']){await patch('dfqi_program_config',`key=eq.${key}`,{value:f.get(key)||null,updated_at:new Date().toISOString()},session.access_token)}await loadDashboard();alert('Programme configuration saved.')}
function exportContacts(){const rows=snapshot.contacts.map(c=>{const a=latestFor(snapshot.assessments,c.id),i=latestFor(snapshot.intents,c.id);return{full_name:c.full_name,email:c.email,phone:c.phone,organisation:c.organization_name,role:c.role_title,part1_status:c.part1_status,readiness_score:a?.score??'',recommended_route:a?.recommended_route??'',programme_intent:i?.requested_program??'',intent_status:i?.status??'',handoff:i?.registration_handoff_status??'',first_source:c.first_source??''}});const keys=Object.keys(rows[0]||{});if(!keys.length)return;const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='dfqi-contacts.csv';a.click();URL.revokeObjectURL(u)}
