import {rpc,select,signIn} from './api.js';
import {visitorId,attribution,setLastRoute,getLastRoute} from './state.js';
import {renderQuestions,answersFromForm,routeCopy} from './readiness.js';
import {bindAdminUI,tryRestoreAdmin,enterAdmin} from './admin.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const attr=attribution(); const visitor=visitorId();
function route(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${name}`);if(name==='admin')tryRestoreAdmin()}
function success(host,title,body){host.innerHTML=`<div class="result-card success"><h3>${title}</h3><p>${body}</p></div>`}
function error(host,e){host.innerHTML=`<div class="result-card error"><h3>We could not complete that action.</h3><p>${String(e.message||e)}</p></div>`}
async function logEvent(event_name,routeName=null,metadata={}){try{await rpc('dfqi_log_event',{p_visitor_id:visitor,p_event_name:event_name,p_route:routeName,p_source:attr.source,p_medium:attr.medium,p_campaign:attr.campaign,p_content:attr.content,p_metadata:metadata})}catch{}}
function pathwayPayload(f,pathway,part1Status,fundingRoute='unknown'){
 return {p_visitor_id:visitor,p_full_name:f.get('full_name'),p_email:f.get('email'),p_phone:f.get('phone')||null,p_organization_name:f.get('organization_name')||null,p_role_title:f.get('role_title')||null,p_part1_status:part1Status,p_requested_program:programFor(pathway),p_pathway:pathway,p_funding_route:fundingRoute,p_notes:null,p_source:attr.source,p_medium:attr.medium,p_campaign:attr.campaign,p_consent_to_contact:f.get('consent')==='on'}
}
function programFor(pathway){return pathway==='part1'?'part1':pathway==='foundation_bridge'?'foundation_bridge':pathway==='mini_masterclass'?'mini_masterclass':'part2'}
function openLead(pathway){setLastRoute(pathway);const dlg=$('#lead-dialog');dlg.querySelector('[name=pathway]').value=pathway;const labels={equivalency:'Request direct-entry / equivalency review',foundation_bridge:'Join the Foundation Bridge interest list',part1:'Join the DFQI Part 1 interest list',mini_masterclass:'Join the DFQI learning community',alumni_refresher:'Register Part 2 + refresher interest'};$('#lead-title').textContent=labels[pathway]||'Register your DFQI interest';$('#lead-message').textContent='';dlg.showModal()}

renderQuestions($('#readiness-questions'));
$$('[data-route]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.pathway)setLastRoute(b.dataset.pathway);route(b.dataset.route)}));
$$('.lead-trigger').forEach(b=>b.onclick=()=>openLead(b.dataset.pathway));

$('#readiness-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,result=$('#readiness-result');form.classList.add('loading');result.innerHTML='';try{const f=new FormData(form),answers=answersFromForm(form);const part1=f.get('part1')==='yes';const res=await rpc('dfqi_submit_readiness',{p_visitor_id:visitor,p_part1_completed:part1,p_role_title:f.get('role')||null,p_answers:answers});setLastRoute(res.route);const c=routeCopy[res.route];result.innerHTML=`<div class="result-card"><span class="tag">${res.score}% readiness indicator · ${c.tag}</span><h2>${c.title}</h2><p>${c.body}</p><div class="button-row"><button class="btn primary" id="route-cta">${c.cta}</button><button class="btn secondary" id="masterclass-cta">Explore free Mini-Masterclasses</button></div></div>`;$('#route-cta').onclick=()=>{logEvent('route_selected',res.route,{score:res.score});if(c.route==='enrol'){document.querySelector('#enrol-form [name=pathway]').value=res.route;route('enrol')}else if(c.route==='bridge')route('bridge');else openLead(res.route)};$('#masterclass-cta').onclick=()=>route('community')}catch(err){error(result,err)}finally{form.classList.remove('loading')}};

$('#lead-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,msg=$('#lead-message'),f=new FormData(form),pathway=f.get('pathway');msg.textContent='Saving…';try{const part1Status=pathway==='alumni_refresher'?'completed':(['equivalency','foundation_bridge','part1'].includes(pathway)?'not_completed':'unknown');if(pathway==='mini_masterclass'){await rpc('dfqi_submit_masterclass_interest',{p_visitor_id:visitor,p_full_name:f.get('full_name'),p_email:f.get('email'),p_phone:f.get('phone')||null,p_organization_name:f.get('organization_name')||null,p_role_title:f.get('role_title')||null,p_part1_status:part1Status,p_session_slug:'weekend-series',p_source:attr.source,p_medium:attr.medium,p_campaign:attr.campaign,p_consent_to_contact:f.get('consent')==='on'})}else{await rpc('dfqi_submit_pathway_interest',pathwayPayload(f,pathway,part1Status))}msg.textContent='Saved. Your DFQI pathway is now recorded for follow-up.';setTimeout(()=>{$('#lead-dialog').close();form.reset()},1000)}catch(err){msg.textContent=err.message||String(err)}};

$('#enrol-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,result=$('#enrol-result'),f=new FormData(form),pathway=f.get('pathway')||getLastRoute()||'part2';form.classList.add('loading');try{const safePathway=['part2','alumni_refresher','equivalency'].includes(pathway)?pathway:'part2';const payload=pathwayPayload(f,safePathway,f.get('part1_status'),f.get('funding_route'));payload.p_requested_program='part2';await rpc('dfqi_submit_pathway_interest',payload);success(result,'Your Part 2 interest is recorded.','The programme team can now follow up on pathway confirmation, equivalency where relevant and the external administrative registration process. No payment was handled here.');form.reset()}catch(err){error(result,err)}finally{form.classList.remove('loading')}};

$('#organisation-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,result=$('#organisation-result'),f=new FormData(form);form.classList.add('loading');try{await rpc('dfqi_submit_organisation_interest',{p_organization_name:f.get('organization_name'),p_contact_name:f.get('contact_name'),p_email:f.get('email'),p_phone:f.get('phone')||null,p_team_size:f.get('team_size')?Number(f.get('team_size')):null,p_primary_need:f.get('primary_need'),p_notes:f.get('notes')||null,p_source:attr.source,p_medium:attr.medium,p_campaign:attr.campaign});success(result,'Organisation request received.','The request has been captured as an organisational lead rather than an individual consumer enrolment.');form.reset()}catch(err){error(result,err)}finally{form.classList.remove('loading')}};

$('#admin-login-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,msg=$('#admin-auth-message'),f=new FormData(form);msg.textContent='Signing in…';try{const data=await signIn(f.get('email'),f.get('password'));await enterAdmin(data);msg.textContent=''}catch(err){msg.textContent=err.message||String(err)}};
bindAdminUI();

(async()=>{try{const cfg=await select('dfqi_program_config','select=key,value&is_public=eq.true');window.DFQI_CONFIG=Object.fromEntries(cfg.map(x=>[x.key,x.value]))}catch{}await logEvent('page_view',null,{path:location.hash||'#home'});const initial=location.hash.replace('#','');route(['home','readiness','bridge','enrol','community','organisation','admin'].includes(initial)?initial:'home')})();
